---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: brianbyers/concourse-gradle
    tag: "latest"


caches:
  - path: .gradle
  - path: .m2
  
outputs:
  - name: artifact-dir

caches:
  - path: /.gradle/
  - path: /.m2/
run:
  path: git-repo/ci/scripts/build-artifact.sh

params:
  base_name:
