---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: brianbyers/concourse-gradle
    tag: "latest"

inputs:
  - name: git-repo
caches:
  - path: .gradle/
  - path: .m2/

run:
  path: git-repo/ci/scripts/unit.sh
